rm whitepaper.aux
rm whitepaper.out
rm whitepaper.log
rm wpwhitepaper.bbl
rm whitepaper.blg
pdflatex whitepaper
bibtex whitepaper
pdflatex whitepaper
pdflatex whitepaper
rm whitepaper.aux
rm whitepaper.out
rm whitepaper.log
rm whitepaper.bbl
rm whitepaper.blg
